plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.11'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.openapi.generator' version '7.20.0'
}

group = 'com.basov.sav'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'io.swagger.core.v3:swagger-annotations:2.2.15'
	implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

openApiGenerate {
	generatorName.set('spring')
	remoteInputSpec.set('https://api-prod.arvato.ru/resources/openapi/openapi.json')
	ignoreFileOverride.set(".openapi-generator-java-sources.ignore")
	invokerPackage.set('com.myapp')
	modelPackage.set('com.myapp.model')
	apiPackage.set('com.myapp.api')
	configOptions.set([
			interfaceOnly: "true",
			useSpringBoot3: "true",
			useJakartaEe: "true",
			serializableModel: "true",
			skipDefaultInterface: "true",
			openApiNullable: "false"
	])

	globalProperties = [
			apiTests: "false",
			modelTests: "false",
			apiDocs: "false",
			modelDocs: "false"
	]
}

sourceSets.main.java.srcDir "${buildDir}/generate-resources/main/src/main/java"

tasks.named('test') {
	useJUnitPlatform()
}

tasks.named('compileJava') {
	dependsOn(tasks.openApiGenerate)
}